Обратная сторона реальности
htmlacademy-react/1189877-what-to-watch-6 pull request #5
Opened 2021-02-15 14:45 UTC by darya023

Добавлены: 
* моки, 
* компоненты Films, Logo, User и ReviewForm,  
* state для компонентов Films, ReviewForm.

Cделана перелинковка страниц.

2021-02-16 18:21 UTC, vatokato requested changes

2021-02-16 18:21 UTC, vatokato commented on src/components/films/films.jsx
> +          activeFilm={activeMovieCard}
В конечных компонентах нужно стараться оставлять как можно меньше логики:
вместо передачи айди активного фильма и сравнения там, лучше сравнить тут, а в компонент передать флаг активности:
`isActive={activeMovieCard === id}`

не очень критично, но важно вцелом

2021-02-16 18:21 UTC, vatokato commented on src/components/films/films.jsx
> +  const [activeMovieCard, setActiveMovieCard] = useState(``);
точнее `activeMovieCardId`, все таки ты сохраняешь не весь объект, а только айди

не критично

2021-02-16 18:21 UTC, vatokato commented on src/components/player-screen/player-screen.jsx
> +const PlayerScreen = ({films, ...props}) => {
в этот компонент должны приходить пропы одного фильма, фильтрацию нужно устроить на верхнем уровне (App). 

Вот пример как сделать более правильно (можем без проблем прикрутить обработку 404):
```
<Route exact path={....}
  render={(routerProps)=>{
    const film = films.find(film => film.id === routeProps.match.params.id);
    return (
      film ? <PlayerScreen {...film} ... /> : <404 />
    );
}}/>
```
обрати внимание, что не обязательно передавать пропсы роутера в компонент, можно использовать их раньше
если что дока: https://reactrouter.com/web/api/Route/render-func

2021-02-16 18:21 UTC, vatokato commented on src/components/add-review-screen/add-review-screen.jsx
> +  const currentFilmId = props.match.params.id;
аналогично, в конкретный компонент должны приходить конкретные данные

2021-02-16 18:21 UTC, vatokato commented on src/components/review-form/review-form.jsx
> +    onSubmit(reviewText);
а где же передача оценки? )

вот примерчик, не обязательно его использовать, но разобраться с ним было бы здорово:
```
const [formData, setFormValue] = useState({
    rating: ``,
    text: ``
  });


setFormValue((state) => ({...state, [name]: value}));
```

2021-02-17 08:46 UTC, darya023 commented on src/components/films/films.jsx
> +          activeFilm={activeMovieCard}
Исправлено

2021-02-17 08:46 UTC, darya023 commented on src/components/films/films.jsx
> +  const [activeMovieCard, setActiveMovieCard] = useState(``);
Исправлено

2021-02-17 09:55 UTC, darya023 commented on src/components/player-screen/player-screen.jsx
> +const PlayerScreen = ({films, ...props}) => {
Здорово, это намного лучше, чем было у меня. Теперь поняла момент с подготовкой данных, пропсами роутера, спасибо :) Исправила везде

2021-02-17 09:55 UTC, darya023 commented on src/components/add-review-screen/add-review-screen.jsx
> +  const currentFilmId = props.match.params.id;
Исправлено

2021-02-17 12:14 UTC, darya023 commented on src/components/review-form/review-form.jsx
> +    onSubmit(reviewText);
ой, оценка потерялась.. Исправила

2021-02-17 13:17 UTC, vatokato requested changes
Отлично, молодец.

Один коммент :)

2021-02-17 13:17 UTC, vatokato commented on src/components/app/app.jsx
> +              const [currentFilm] = films.filter((film) => film.id === id);
почему `filter`? `find` в этом случае (в любом где нужно найти 1 элемент) более правильно:
filter обходит весь массив до конца, find же вернет результат сразу как только произойдет первое совпадениbt.

2021-02-17 13:31 UTC, darya023 commented on src/components/app/app.jsx
> +              const [currentFilm] = films.filter((film) => film.id === id);
Исправила

2021-02-17 13:45 UTC, merged