Больше подробностей (часть 2)
htmlacademy-react/1189877-what-to-watch-6 pull request #7
Opened 2021-02-21 18:04 UTC by darya023

Добавлены:
* реализация табов;
* компонент Catalog.

2021-02-22 12:22 UTC, vatokato commented on src/utils/const.js
> +export const Tab = {
константы не должны лежать в папке `utils`, правильнее держать в корне.

2021-02-22 12:34 UTC, vatokato requested changes
В целом хорошо. По паттерну прокси - вообще отлично.

2021-02-22 12:34 UTC, vatokato commented on src/components/tabs/tabs.jsx
> +    <Panel
Лучше разнести контент на 3 разных компонента. сейчас Panel выглядит просто ужасно :)

2021-02-22 12:34 UTC, vatokato commented on src/components/app/app.jsx
> +                ? <FilmScreen currentFilmId={id} films={films} user={user} reviews={currentFilmReviews}/>
а зачем ты сюда передаешь все фильмы, у нас ведь уже есть `currentFilm`, его и передавай.
если тебе нужно выбрать рандомные фильмы, то тогда функцию для фильтрации в utils, а фильмы собирать так же здесь. 
Компонент же должен быть максимально простым

2021-02-22 12:34 UTC, vatokato commented on src/components/film-screen/film-screen.jsx
> +const getRandomFilms = (films, count)=>{
это в `utils`

2021-02-22 12:34 UTC, vatokato commented on src/components/film-screen/film-screen.jsx
> +const getRandomInteger = (a = 0, b = 1) => {
это в `utils`

2021-02-22 12:34 UTC, vatokato commented on src/components/catalog/catalog-small.jsx
> +const CatalogSmall = (props) => {
Отличное решение, только я бы привязал название к `like-this`, так бы было понятнее: `CatalogSimilar` или что то в этом духе

2021-02-22 19:57 UTC, darya023 commented on src/utils/const.js
> +export const Tab = {
Исправлено

2021-02-22 20:13 UTC, darya023 commented on src/components/tabs/tabs.jsx
> +    <Panel
А эти 3 компонента следует использовать здесь, передавая им пропс `isActive` и избавиться от `Panel`, 
или внутри `Panel`, в `switch` https://github.com/htmlacademy-react/1189877-what-to-watch-6/blob/0ad88a9557da11dc349a7c45abc2eabc0f6f48d3/src/components/panel/panel.jsx#L98, компоненты использовать вместо разметки? 
Или вся идея со `switch` плоха?

2021-02-22 20:17 UTC, darya023 commented on src/components/app/app.jsx
> +                ? <FilmScreen currentFilmId={id} films={films} user={user} reviews={currentFilmReviews}/>
Точно... Исправила

2021-02-22 20:17 UTC, darya023 commented on src/components/film-screen/film-screen.jsx
> +const getRandomFilms = (films, count)=>{
Исправлено

2021-02-22 20:18 UTC, darya023 commented on src/components/film-screen/film-screen.jsx
> +const getRandomInteger = (a = 0, b = 1) => {
Исправлено

2021-02-22 20:18 UTC, darya023 commented on src/components/catalog/catalog-small.jsx
> +const CatalogSmall = (props) => {
Исправлено.

2021-02-24 15:43 UTC, vatokato commented on src/components/tabs/tabs.jsx
> +    <Panel
`switch` норм, но лучше тут свитч, а в компоненты передавать только для них необходимые пропсы

2021-02-24 15:45 UTC, vatokato commented on src/components/catalog/catalog-small.jsx
> +const CatalogSmall = (props) => {
как хочешь

2021-02-24 15:46 UTC, vatokato commented on src/components/panel/panel.jsx
> +const humanizeRating = (filmRating) => {
я бы вынес, но не настаиваю

2021-02-24 17:30 UTC, darya023 commented on src/components/tabs/tabs.jsx
> +    <Panel
Исправлено

2021-02-24 17:31 UTC, darya023 commented on src/components/catalog/catalog-small.jsx
> +const CatalogSmall = (props) => {
Ок

2021-02-24 17:31 UTC, darya023 commented on src/components/panel/panel.jsx
> +const humanizeRating = (filmRating) => {
Вынесла

2021-02-24 18:49 UTC, vatokato commented on src/utils/details-panel.js
> +export const humanizeDuration = (filmDuration) => {
почему аргумент filmDuration? ведь функция подходит для любого duration )

2021-02-24 18:49 UTC, vatokato commented on src/components/catalog/catalog-small.jsx
> +const CatalogSmall = (props) => {
круто

2021-02-24 18:49 UTC, vatokato commented on src/components/app/app.jsx
> +                ? <FilmScreen currentFilmId={id} films={films} user={user} reviews={currentFilmReviews}/>
круто

2021-02-24 19:02 UTC, merged

2021-02-25 07:24 UTC, darya023 commented on src/utils/details-panel.js
> +export const humanizeDuration = (filmDuration) => {
Исправила