Истина где-то на сервере
htmlacademy-react/1189877-what-to-watch-6 pull request #9
Opened 2021-03-04 11:43 UTC by darya023

* Подключены axios и redux-thunk, 
* добавлен модуль Api, 
* реализована загрузка списка фильмов с сервера, 
* добавлен компонент Spinner.

2021-03-04 17:28 UTC, darya023 commented on src/utils/adaptDataToClient.js
> +export const adaptDataToClient = (film) => {
Изменила адаптер

2021-03-04 17:34 UTC, darya023 reviewed
И еще вопрос.  С сервера приходит background_color. Где его использовать?)

2021-03-04 17:34 UTC, darya023 commented on src/components/details-panel/details-panel.jsx
>    duration,
Пропсы у панелей стоит получать из хранилища или прокидывать от FilmScreen => Tabs => панели?

2021-03-05 12:42 UTC, vatokato commented on src/store/reducer.js
> +        currentFilm: filter[FilterType.ID](state, action.payload),
вот тут я не понимаю что происходит, почему именно так?
если нам нужно сохранить фильм, то почему просто не найти фильм по айди и сохранить сюда. А еще лучше сохранять `currentFilmId`, а когда нужно икать нужный по этому идентификатору. Ведь сейчас получается у нас хранится фильм в двух местах: в списке и тут.

2021-03-05 12:50 UTC, vatokato requested changes
В целом хорошо, но я не понял зачем ты добавила добавление в стейт фильтра `SIMILAR`? можно ведь вообще без него: выводить похожие просто фильтруя фильмы из стора по текущему фильму. Тогда бы фильтры по жанрам не сбрасывались и можно было вернуться назад. 

лучше переделать.

2021-03-05 12:50 UTC, vatokato commented on src/utils/filter.js
> +export const filter = {
В целом реализация фильров мне нравится. молодец

2021-03-05 12:56 UTC, vatokato commented on src/components/details-panel/details-panel.jsx
>    duration,
устанавливать в <div className="movie-card__bg"> пропсом. в `MainScreen`

2021-03-05 13:32 UTC, darya023 commented on src/utils/filter.js
> +export const filter = {
По моей задумке в `SIMILAR` кроме фильтрации по жанрам еще убирается текущий фильм из списка

2021-03-05 14:09 UTC, darya023 commented on src/components/details-panel/details-panel.jsx
>    duration,
Поняла, разобрались) Только ты наверное про `FilmScreen`

2021-03-05 14:56 UTC, merged

2021-03-06 12:19 UTC, darya023 commented on src/store/reducer.js
> +        currentFilm: filter[FilterType.ID](state, action.payload),
Изменила поиск текущего фильма и убрала его из хранилища. Посмотри, пожалуйста, в следующем пул реквесте